export { default as happy_child } from "../assets/happy.webp";
export { default as headphone } from "../assets/headphone.webp";
export { default as ipsum } from "../assets/Logo.png";
export { default as Ipsum } from "../assets/ipsum.png";
export { default as lorem } from "../assets/Logo (4).png";
export { default as oldIpsum } from "../assets/Logo (3).png";
export { default as newIpsum } from "../assets/Logo (2).png";
export { default as mission } from "../assets/mission.webp";
export { default as escort } from "../assets/excort.png";
export { default as ngo_award } from "../assets/ngo.png";
export { default as best_award } from "../assets/best.png";
export { default as csn_award } from "../assets/csn.png";
export { default as global_award } from "../assets/global.png";
export { default as care } from "../assets/care.png";
export { default as adrian } from "../assets/adrian.png";
export { default as ellen } from "../assets/ellen.png";
export { default as francis } from "../assets/francis.png";
export { default as freddy } from "../assets/freddy.png";
export { default as john } from "../assets/john.png";
export { default as kylie } from "../assets/kylie.png";
export { default as miriam } from "../assets/miriam.png";
export { default as dale } from "../assets/dale.png";
